name:                hasklox
version:             0.1.0.0
github:              "sayantangkhan/hasklox"
license:             CC0-1.0
author:              "Sayantan Khan"
maintainer:          "sayantangkhan@gmail.com"
copyright:           "2022 Sayantan Khan"

extra-source-files:
- README.md
- CHANGELOG.md
- src/HaskLox/Scanner.x
- src/HaskLox/Parser.y

default-extensions:
- OverloadedStrings
- ImportQualifiedPost

# Metadata used when publishing your package
synopsis:            Haskell implementation of the Lox interpreter from 'Crafting Interpreters'
category:            Compilers/Interpreters

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sayantangkhan/hasklox#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- array
- text
- mtl

build-tools:
  - alex
  - happy

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hasklox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasklox

tests:
  hasklox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hasklox
